name: "Apps: Test Push"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ixsystems/catalog_validation:latest

    steps:
    - uses: actions/checkout@v7
      name: Checkout
      
    - name: Generate catalog metadata
      run: catalog_update update --path "$GITHUB_WORKSPACE"

    - name: Validate catalog format
      run: |
        catalog_validate validate --path "$GITHUB_WORKSPACE"
